/******************************************************************************
 * @file    ISP3010-UX-TG.h
 * @author  Insight SiP
 * @brief   ISP3080 TAG board specific file.
 *
 * @attention
 *  THIS SOFTWARE IS PROVIDED BY INSIGHT SIP "AS IS" AND ANY EXPRESS
 *  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED. IN NO EVENT SHALL INSIGHT SIP OR CONTRIBUTORS BE
 *  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 *  GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 *  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 *  OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

#ifndef ISP3010_UX_TAG_H
#define ISP3010_UX_TAG_H

#include "isp3080-ux.h"

// Boards specific pinout
#define PIN_CURR_MODE NRF_GPIO_PIN_MAP(0, 6)
#define PIN_BATT_MEAS NRF_GPIO_PIN_MAP(0, 2)
#define PIN_GREEN_LED NRF_GPIO_PIN_MAP(0, 12)
#define PIN_RED_LED NRF_GPIO_PIN_MAP(0, 8)

// Battery measurement
// Vmeas = R2/(R2+R1)*Vbatt
#define BATT_VOLTAGE_DIVIDER_R1 4300000
#define BATT_VOLTAGE_DIVIDER_R2 10000000

#endif