/******************************************************************************
 * @file    isp3080-ux.h
 * @author  Insight SiP
 * @brief   ISP3010-UX module specific file.
 * @version C
 *
 * @attention
 *  THIS SOFTWARE IS PROVIDED BY INSIGHT SIP "AS IS" AND ANY EXPRESS
 *  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED. IN NO EVENT SHALL INSIGHT SIP OR CONTRIBUTORS BE
 *  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 *  GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 *  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 *  OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

#ifndef ISP3080_UX_H
#define ISP3080_UX_H

#include "nrf_gpio.h"

// internal pinout to DW3000
#define PIN_DW3000_CLK NRF_GPIO_PIN_MAP(0, 19)
#define PIN_DW3000_IRQ NRF_GPIO_PIN_MAP(1, 1)
#define PIN_DW3000_RST NRF_GPIO_PIN_MAP(0, 23)
#define PIN_DW3000_MOSI NRF_GPIO_PIN_MAP(0, 16)
#define PIN_DW3000_WAKEUP NRF_GPIO_PIN_MAP(0, 29)
#define PIN_DW3000_CS NRF_GPIO_PIN_MAP(0, 20)
#define PIN_DW3000_MISO NRF_GPIO_PIN_MAP(0, 13)

#if (MODULE_ISP3080_UX_REV >= 2)
// internal pinout to lis2de12
#define PIN_LIS2DE12_EN NRF_GPIO_PIN_MAP(1, 6)
#define PIN_LIS2DE12_INT1 NRF_GPIO_PIN_MAP(0, 24)
#define PIN_LIS2DE12_INT2 NRF_GPIO_PIN_MAP(1, 4)
#define PIN_LIS2DE12_SCL NRF_GPIO_PIN_MAP(1, 7)
#define PIN_LIS2DE12_SDA NRF_GPIO_PIN_MAP(1, 2)
#endif

#endif